# Generated by Django 3.0.3 on 2020-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
