# Generated by Django 3.0.3 on 2020-03-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='shop',
            field=models.IntegerField(choices=[(0, 'なし'), (10, 'BOOTH'), (20, 'DLSite'), (30, 'FANZA電子書籍'), (31, 'FANZA同人'), (40, 'メロンブックス')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='circle',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.IntegerField(choices=[(0, 'なし'), (10, 'BOOTH'), (20, 'DLSite'), (30, 'FANZA電子書籍'), (31, 'FANZA同人'), (40, 'メロンブックス')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
